[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  query = {fingerprint = ":hash"}
  to = "https://:hash--test-fingerprint.netlify.app/:splat?"
  status = 200
  force = true